name: quality-assembly-tools
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - salsa2
  - bowtie
  - python>=3.5
    - pip
    - mpi4py
    - matplotlib<=3.2.1
    - numpy==1.16.6
    - scipy
    - yt
    - pandas
    - pip:
        - trident
        - spectacle
        - specutils==0.5.2
        - gwcs==0.10.0
        - astropy==3.2.3
